- name: install bonding dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - vim
    - ifenslave-2.6

- name: ensure kernel bonding
  lineinfile: dest=/etc/modules regexp='bonding' line='bonding'

- name: setup interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=0644
